<#
.SYNOPSIS
    Writes a mermaid diagram into the current Copilot session folder and opens it
    rendered in VS Code / VS Code Insiders.

.DESCRIPTION
    Mermaid rendering is built into VS Code (the `mermaid-markdown-features`
    extension ships with the product), so nothing needs installing.

    To open the file *rendered* rather than as source, this script generates a
    small workspace whose `workbench.editorAssociations` maps `*.diagram.md` to
    the `vscode.markdown.preview.editor` custom editor. There is no CLI flag to
    invoke the "open preview" command directly, so the association is the
    mechanism that makes it work.

.PARAMETER Name
    Diagram name; becomes <Name>.diagram.md. Defaults to a timestamp.

.PARAMETER Mermaid
    The mermaid source, WITHOUT the surrounding ```mermaid fence.

.PARAMETER MermaidFile
    Read the mermaid source from this file instead of -Mermaid.

.PARAMETER Title
    Optional heading placed above the diagram.

.PARAMETER SessionPath
    Current Copilot session folder. Falls back to the most recent one.

.PARAMETER Editor
    'auto' (default, prefers Insiders), 'insiders', or 'code'.

.PARAMETER DryRun
    Write the file but do not launch an editor.
#>
[CmdletBinding()]
param(
    [string]$Name,
    [string]$Mermaid,
    [string]$MermaidFile,
    [string]$Title,
    [string]$SessionPath,
    [ValidateSet('auto', 'insiders', 'code')]
    [string]$Editor = 'auto',
    [switch]$ForcePreviewWorkspace,
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\common.ps1"

try {
    if (-not $Mermaid -and -not $MermaidFile) {
        throw "Provide the diagram source with -Mermaid '<mermaid code>' or -MermaidFile <path>."
    }
    if ($MermaidFile) {
        if (-not (Test-Path -LiteralPath $MermaidFile)) {
            throw "Mermaid source file does not exist: $MermaidFile"
        }
        $Mermaid = Get-Content -LiteralPath $MermaidFile -Raw
    }

    $Mermaid = $Mermaid.Trim()
    if (-not $Mermaid) { throw "The mermaid source is empty." }

    # Tolerate callers that wrapped the source in a fence anyway.
    if ($Mermaid -match '^\s*```') {
        $Mermaid = ($Mermaid -replace '^\s*```[\w]*\s*\r?\n', '') -replace '\r?\n\s*```\s*$', ''
        $Mermaid = $Mermaid.Trim()
    }

    $sessionFolder = Resolve-SessionFolder -Explicit $SessionPath
    if (-not $sessionFolder) {
        throw "No Copilot session folder found. Pass -SessionPath explicitly."
    }

    # Session artifacts belong in files/ when it exists.
    $targetDir = Join-Path $sessionFolder 'files'
    if (-not (Test-Path -LiteralPath $targetDir)) {
        New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
    }

    if (-not $Name) { $Name = 'diagram-' + (Get-Date -Format 'yyyyMMdd-HHmmss') }
    $Name = ConvertTo-SafeName ($Name -replace '\.diagram\.md$', '' -replace '\.md$', '')

    $diagramPath = Join-Path $targetDir "$Name.diagram.md"

    $heading = if ($Title) { $Title } else { $Name }
    $body = @"
# $heading

``````mermaid
$Mermaid
``````

<sub>Generated by porthole - $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')</sub>
"@

    [IO.File]::WriteAllText($diagramPath, $body, (New-Object System.Text.UTF8Encoding($false)))

    Write-Host "Diagram  : $diagramPath"

    if ($DryRun) {
        Write-Host "-DryRun specified; editor not launched."
        exit 0
    }

    $t = Resolve-EditorTarget -Preference $Editor -ContextPath $targetDir

    if ($t.Connected -and -not $ForcePreviewWorkspace) {
        # An IDE is already connected. Opening a different .code-workspace here
        # would spawn a second window, so reuse the existing one instead.
        Write-Host "IDE      : reusing connected $($t.IdeName) window"
        Invoke-Editor -EditorCommand $t.Command -Arguments @('--reuse-window', $diagramPath)

        if (-not (Test-UserPreviewAssociation)) {
            Write-Host ""
            Write-Host "Note: the diagram opened in the connected window. If it shows as source"
            Write-Host "      rather than rendered, either press Ctrl+Shift+V, or run setup once:"
            Write-Host "      scripts/setup.ps1 -RegisterDiagramPreview"
        }
        Write-Host "Opened '$Name' in VS Code."
        exit 0
    }

    # No IDE connected (or explicitly forced): open a small workspace carrying the
    # editor association, so the file opens rendered.
    $wsDir = Get-PortholeTempDir -Leaf 'porthole-workspaces'
    $wsFile = Join-Path $wsDir ("diagrams-{0}.code-workspace" -f (Get-ShortId (Split-Path -Leaf $sessionFolder)))

    $workspace = [ordered]@{
        folders  = @([ordered]@{ path = $targetDir; name = 'Session Diagrams' })
        settings = [ordered]@{
            'workbench.editorAssociations' = [ordered]@{
                '*.diagram.md' = 'vscode.markdown.preview.editor'
            }
        }
    }
    Write-JsonFile -Path $wsFile -Object $workspace
    Write-Host "Workspace: $wsFile"

    Invoke-Editor -EditorCommand $t.Command -Arguments @($wsFile)
    Start-Sleep -Milliseconds 1200
    Invoke-Editor -EditorCommand $t.Command -Arguments @('--reuse-window', $diagramPath)

    Write-Host "Opened '$Name' rendered in VS Code."
}
catch {
    Write-Host "porthole diagram: $($_.Exception.Message)"
    exit 1
}
